package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallEtmPayee;
import org.linlinjava.litemall.db.domain.LitemallEtmPayeeExample;

public interface LitemallEtmPayeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_etm_payee
     *
     * @mbg.generated
     */
    long countByExample(LitemallEtmPayeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_etm_payee
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallEtmPayeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_etm_payee
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_etm_payee
     *
     * @mbg.generated
     */
    int insert(LitemallEtmPayee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_etm_payee
     *
     * @mbg.generated
     */
    int insertSelective(LitemallEtmPayee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_etm_payee
     *
     * @mbg.generated
     */
    LitemallEtmPayee selectOneByExample(LitemallEtmPayeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_etm_payee
     *
     * @mbg.generated
     */
    LitemallEtmPayee selectOneByExampleSelective(@Param("example") LitemallEtmPayeeExample example, @Param("selective") LitemallEtmPayee.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_etm_payee
     *
     * @mbg.generated
     */
    List<LitemallEtmPayee> selectByExampleSelective(@Param("example") LitemallEtmPayeeExample example, @Param("selective") LitemallEtmPayee.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_etm_payee
     *
     * @mbg.generated
     */
    List<LitemallEtmPayee> selectByExample(LitemallEtmPayeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_etm_payee
     *
     * @mbg.generated
     */
    LitemallEtmPayee selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") LitemallEtmPayee.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_etm_payee
     *
     * @mbg.generated
     */
    LitemallEtmPayee selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_etm_payee
     *
     * @mbg.generated
     */
    LitemallEtmPayee selectByPrimaryKeyWithLogicalDelete(@Param("id") Long id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_etm_payee
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallEtmPayee record, @Param("example") LitemallEtmPayeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_etm_payee
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallEtmPayee record, @Param("example") LitemallEtmPayeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_etm_payee
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallEtmPayee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_etm_payee
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallEtmPayee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_etm_payee
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallEtmPayeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_etm_payee
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Long id);
}