package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallOrderEtm;
import org.linlinjava.litemall.db.domain.LitemallOrderEtmExample;

public interface LitemallOrderEtmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_etm
     *
     * @mbg.generated
     */
    long countByExample(LitemallOrderEtmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_etm
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallOrderEtmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_etm
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_etm
     *
     * @mbg.generated
     */
    int insert(LitemallOrderEtm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_etm
     *
     * @mbg.generated
     */
    int insertSelective(LitemallOrderEtm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_etm
     *
     * @mbg.generated
     */
    LitemallOrderEtm selectOneByExample(LitemallOrderEtmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_etm
     *
     * @mbg.generated
     */
    LitemallOrderEtm selectOneByExampleSelective(@Param("example") LitemallOrderEtmExample example, @Param("selective") LitemallOrderEtm.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_etm
     *
     * @mbg.generated
     */
    List<LitemallOrderEtm> selectByExampleSelective(@Param("example") LitemallOrderEtmExample example, @Param("selective") LitemallOrderEtm.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_etm
     *
     * @mbg.generated
     */
    List<LitemallOrderEtm> selectByExample(LitemallOrderEtmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_etm
     *
     * @mbg.generated
     */
    LitemallOrderEtm selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallOrderEtm.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_etm
     *
     * @mbg.generated
     */
    LitemallOrderEtm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_etm
     *
     * @mbg.generated
     */
    LitemallOrderEtm selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_etm
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallOrderEtm record, @Param("example") LitemallOrderEtmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_etm
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallOrderEtm record, @Param("example") LitemallOrderEtmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_etm
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallOrderEtm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_etm
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallOrderEtm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_etm
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallOrderEtmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_order_etm
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}