package org.linlinjava.litemall.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallDraw {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_draw.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_draw.userId
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_draw.secret
     *
     * @mbg.generated
     */
    private String secret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_draw.amount
     *
     * @mbg.generated
     */
    private String amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_draw.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_draw.transactionId1
     *
     * @mbg.generated
     */
    private String transactionid1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_draw.transactionId2
     *
     * @mbg.generated
     */
    private String transactionid2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_draw.transactionId3
     *
     * @mbg.generated
     */
    private String transactionid3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_draw.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_draw.id
     *
     * @return the value of litemall_draw.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_draw.id
     *
     * @param id the value for litemall_draw.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_draw.userId
     *
     * @return the value of litemall_draw.userId
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_draw.userId
     *
     * @param userid the value for litemall_draw.userId
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_draw.secret
     *
     * @return the value of litemall_draw.secret
     *
     * @mbg.generated
     */
    public String getSecret() {
        return secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_draw.secret
     *
     * @param secret the value for litemall_draw.secret
     *
     * @mbg.generated
     */
    public void setSecret(String secret) {
        this.secret = secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_draw.amount
     *
     * @return the value of litemall_draw.amount
     *
     * @mbg.generated
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_draw.amount
     *
     * @param amount the value for litemall_draw.amount
     *
     * @mbg.generated
     */
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_draw.address
     *
     * @return the value of litemall_draw.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_draw.address
     *
     * @param address the value for litemall_draw.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_draw.transactionId1
     *
     * @return the value of litemall_draw.transactionId1
     *
     * @mbg.generated
     */
    public String getTransactionid1() {
        return transactionid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_draw.transactionId1
     *
     * @param transactionid1 the value for litemall_draw.transactionId1
     *
     * @mbg.generated
     */
    public void setTransactionid1(String transactionid1) {
        this.transactionid1 = transactionid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_draw.transactionId2
     *
     * @return the value of litemall_draw.transactionId2
     *
     * @mbg.generated
     */
    public String getTransactionid2() {
        return transactionid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_draw.transactionId2
     *
     * @param transactionid2 the value for litemall_draw.transactionId2
     *
     * @mbg.generated
     */
    public void setTransactionid2(String transactionid2) {
        this.transactionid2 = transactionid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_draw.transactionId3
     *
     * @return the value of litemall_draw.transactionId3
     *
     * @mbg.generated
     */
    public String getTransactionid3() {
        return transactionid3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_draw.transactionId3
     *
     * @param transactionid3 the value for litemall_draw.transactionId3
     *
     * @mbg.generated
     */
    public void setTransactionid3(String transactionid3) {
        this.transactionid3 = transactionid3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_draw.add_time
     *
     * @return the value of litemall_draw.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_draw.add_time
     *
     * @param addTime the value for litemall_draw.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_draw
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userid=").append(userid);
        sb.append(", secret=").append(secret);
        sb.append(", amount=").append(amount);
        sb.append(", address=").append(address);
        sb.append(", transactionid1=").append(transactionid1);
        sb.append(", transactionid2=").append(transactionid2);
        sb.append(", transactionid3=").append(transactionid3);
        sb.append(", addTime=").append(addTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_draw
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallDraw other = (LitemallDraw) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getSecret() == null ? other.getSecret() == null : this.getSecret().equals(other.getSecret()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getTransactionid1() == null ? other.getTransactionid1() == null : this.getTransactionid1().equals(other.getTransactionid1()))
            && (this.getTransactionid2() == null ? other.getTransactionid2() == null : this.getTransactionid2().equals(other.getTransactionid2()))
            && (this.getTransactionid3() == null ? other.getTransactionid3() == null : this.getTransactionid3().equals(other.getTransactionid3()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_draw
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getSecret() == null) ? 0 : getSecret().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getTransactionid1() == null) ? 0 : getTransactionid1().hashCode());
        result = prime * result + ((getTransactionid2() == null) ? 0 : getTransactionid2().hashCode());
        result = prime * result + ((getTransactionid3() == null) ? 0 : getTransactionid3().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_draw
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        userid("userId", "userid", "INTEGER", false),
        secret("secret", "secret", "VARCHAR", false),
        amount("amount", "amount", "VARCHAR", false),
        address("address", "address", "VARCHAR", false),
        transactionid1("transactionId1", "transactionid1", "VARCHAR", false),
        transactionid2("transactionId2", "transactionid2", "VARCHAR", false),
        transactionid3("transactionId3", "transactionid3", "VARCHAR", false),
        addTime("add_time", "addTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_draw
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_draw
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_draw
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_draw
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_draw
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_draw
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_draw
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_draw
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_draw
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_draw
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_draw
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_draw
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_draw
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_draw
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_draw
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_draw
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}